[project]
name = "estate.service"
version = "0.1.0"
description = "Оценка стоимости недвижимости (ML PRO, ДЗ 1, задание 5)"
requires-python = ">=3.11,<3.13"

dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "pandas",
    "numpy",
    "scikit-learn>=1.6,<1.7",
    "joblib",
    "psycopg[binary]"
]

[dependency-groups]
dev = [
    "pytest",
    "httpx",
    "locust",
    "jupyter",
    "shap",
    "matplotlib",
    "seaborn",
    "ruff",
]

[build-system]
requires = ["uv-build>=0.10,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "estate"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.roof]
line-length = 100

[tool.roof.lint]
select = ["E", "F", "I", "B", "UP"]